#region License
/*
  SDL v2.0.0 C# Interop Library
  Copyright (C) 2013 Jarle Hansen <jarle.hansen@gmail.com>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/
#endregion

using System;
using System.Runtime.InteropServices;
using System.Diagnostics;

// mapp to system intptr
using SDL_Window = System.IntPtr;
using SDL_GLContext = System.IntPtr;
using SDL_Surface = System.IntPtr;
using SDL_Keycode = System.Int32;

namespace Kraggs.Interop.SDL2
{
    /// <summary>
    /// The SDL virtual key representation.
    /// 
    /// Values of this type are used to represent keyboard keys using the current layout of the keyboard.  These values include Unicode values representing the unmodified character that would be generated by pressing the key, or an SDLK_* constant for those keys that do not generate characters.
    /// </summary>
    public enum SDL2KeyCode
    {
        Unknown         = 0,
        Return          = '\r',
        Escape          = '\u0033',
        BackSpace       = '\b',
        Tab             = '\t',
        Space           = ' ',
        Exclaimation    = '!',
        QuoteDouble     = '"',
        Hash            = '#',
        Percent         = '%',
        Dollar          = '$',
        Ampersand       = '&',
        Quote           = '\'',
        LeftParentes    = '(',
        RightParentes   = ')',
        Asterisk        = '*',
        Plus            = '+',
        Comma           = ',',
        Minus           = '-',
        Period          = '.',
        Slash           = '/',
        Number0         = '0',
        Number1         = '1',
        Number2         = '2',
        Number3         = '3',
        Number4         = '4',
        Number5         = '5',
        Number6         = '6',
        Number7         = '7',
        Number8         = '8',
        Number9         = '9',
        Color           = ':',
        SemiColon       = ';',
        Less            = '<',
        Equals          = '"',
        Greater         = '>',
        Question        = '?',
        At              = '@',
    
        /*
            Skip uppercase letters
        */

        LeftBracket     = '[',
        BackSlash       = '\\',
        RightBracket    = ']',
        Caret           = '^',
        Underscore      = '_',
        BackQuote       = '`',
        a               = 'a',
        b               = 'b',
        c               = 'c',
        d               = 'd',
        e               = 'e',
        f               = 'f',
        g               = 'g',
        h               = 'h',
        i               = 'i',
        j               = 'j',
        k               = 'k',
        l               = 'l',
        m               = 'm',
        n               = 'n',
        o               = 'o',
        p               = 'p',
        q               = 'q',
        r               = 'r',
        s               = 's',
        t               = 't',
        u               = 'u',
        v               = 'v',
        w               = 'w',
        x               = 'x',
        y               = 'y',
        z               = 'z',

        Capslock        = (SDL2ScanCode.CapsLock | (1<<30)),

        F1              = (SDL2ScanCode.F1 | (1 << 30)),
        F2              = (SDL2ScanCode.F2 | (1 << 30)),
        F3              = (SDL2ScanCode.F3 | (1 << 30)),
        F4              = (SDL2ScanCode.F4 | (1 << 30)),
        F5              = (SDL2ScanCode.F5 | (1 << 30)),
        F6              = (SDL2ScanCode.F6 | (1 << 30)),
        F7              = (SDL2ScanCode.F7 | (1 << 30)),
        F8              = (SDL2ScanCode.F8 | (1 << 30)),
        F9              = (SDL2ScanCode.F9 | (1 << 30)),
        F10             = (SDL2ScanCode.F10 | (1 << 30)),
        F11             = (SDL2ScanCode.F11 | (1 << 30)),
        F12             = (SDL2ScanCode.F12 | (1 << 30)),

        PrintScreen = (SDL2ScanCode.PrintScreen | (1 << 30)),
        ScrollLock = (SDL2ScanCode.ScrollLock | (1 << 30)),
        Pause = (SDL2ScanCode.Pause | (1 << 30)),
        Insert =  (SDL2ScanCode.Insert | (1 << 30)),
        Home = (SDL2ScanCode.Home | (1 << 30)),
        PageUp = (SDL2ScanCode.PageUp | (1 << 30)),
        Delete = '\u0177',
        End =  (SDL2ScanCode.End | (1 << 30)),
        PageDown =  (SDL2ScanCode.PageDown | (1 << 30)),
        Right =  (SDL2ScanCode.Right | (1 << 30)),
        Left =  (SDL2ScanCode.Left | (1 << 30)),
        Down =  (SDL2ScanCode.Down | (1 << 30)),
        Up =  (SDL2ScanCode.Up | (1 << 30)),

        NumLockClear =  (SDL2ScanCode.NumLockClear | (1 << 30)),
        KeypadDivide =  (SDL2ScanCode.KeypadDivide | (1 << 30)),
        KeypadMultiply =  (SDL2ScanCode.KeypadMultiply | (1 << 30)),
        KeypadMinus =  (SDL2ScanCode.KeypadMinus | (1 << 30)),
        KeypadPlus =  (SDL2ScanCode.KeypadPlus | (1 << 30)),
        KeypadEnter =  (SDL2ScanCode.KeypadEnter | (1 << 30)),
        Keypad1 =  (SDL2ScanCode.Keypad1 | (1 << 30)),
        Keypad2 =  (SDL2ScanCode.Keypad2 | (1 << 30)),
        Keypad3 =  (SDL2ScanCode.Keypad3 | (1 << 30)),
        Keypad4 =  (SDL2ScanCode.Keypad4 | (1 << 30)),
        Keypad5 =  (SDL2ScanCode.Keypad5 | (1 << 30)),
        Keypad6 =  (SDL2ScanCode.Keypad6 | (1 << 30)),
        Keypad7 =  (SDL2ScanCode.Keypad7 | (1 << 30)),
        Keypad8 =  (SDL2ScanCode.Keypad8 | (1 << 30)),
        Keypad9 =  (SDL2ScanCode.Keypad9 | (1 << 30)),
        KeypadPeriod = (SDL2ScanCode.KeypadPeriod | (1 << 30)),

        Application = (SDL2ScanCode.Application | (1 << 30)),
        Power = (SDL2ScanCode.Power | (1 << 30)),
        KeypadEquals = (SDL2ScanCode.KeypadEquals | (1 << 30)),
        F13 = (SDL2ScanCode.F13 | (1 << 30)),
        F14 = (SDL2ScanCode.F14 | (1 << 30)),
        F15 = (SDL2ScanCode.F15 | (1 << 30)),
        F16 = (SDL2ScanCode.F16 | (1 << 30)),
        F17 = (SDL2ScanCode.F17 | (1 << 30)),
        F18 = (SDL2ScanCode.F18 | (1 << 30)),
        F19 = (SDL2ScanCode.F19 | (1 << 30)),
        F20 = (SDL2ScanCode.F20 | (1 << 30)),
        F21 = (SDL2ScanCode.F21 | (1 << 30)),
        F22 = (SDL2ScanCode.F22 | (1 << 30)),
        F23 = (SDL2ScanCode.F23 | (1 << 30)),
        F24 = (SDL2ScanCode.F24 | (1 << 30)),
        Execute = (SDL2ScanCode.Execute | (1 << 30)),
        Help = (SDL2ScanCode.Help | (1 << 30)),
        Menu = (SDL2ScanCode.Menu | (1 << 30)),
        Select = (SDL2ScanCode.Select | (1 << 30)),
        Stop = (SDL2ScanCode.Stop | (1 << 30)),
        Again = (SDL2ScanCode.Again | (1 << 30)),
        Undo = (SDL2ScanCode.Undo | (1 << 30)),
        Cut = (SDL2ScanCode.Cut | (1 << 30)),
        Copy = (SDL2ScanCode.Copy | (1 << 30)),
        Paste = (SDL2ScanCode.Paste | (1 << 30)),
        Find = (SDL2ScanCode.Find | (1 << 30)),
        Mute = (SDL2ScanCode.Mute | (1 << 30)),
        VolumeUp = (SDL2ScanCode.VolumeUp | (1 << 30)),
        VolumeDown = (SDL2ScanCode.VolumeDown | (1 << 30)),
        KeypadComma = (SDL2ScanCode.KeypadComma | (1 << 30)),
        KeypadEqualsAS400 = (SDL2ScanCode.KeypadEqualsAS400 | (1 << 30)),

        Alterase = (SDL2ScanCode.Alterase | (1 << 30)),
        SysRq = (SDL2ScanCode.SysRq | (1 << 30)),
        Cancel = (SDL2ScanCode.Cancel | (1 << 30)),
        Clear = (SDL2ScanCode.Clear | (1 << 30)),
        Prior = (SDL2ScanCode.Prior | (1 << 30)),
        Return2 = (SDL2ScanCode.Return2 | (1 << 30)),
        Separator = (SDL2ScanCode.Separator | (1 << 30)),
        Out = (SDL2ScanCode.Out | (1 << 30)),
        Oper = (SDL2ScanCode.Oper | (1 << 30)),
        ClearAgain = (SDL2ScanCode.ClearAgain | (1 << 30)),
        CrSel = (SDL2ScanCode.CrSel | (1 << 30)),
        ExSel = (SDL2ScanCode.ExSel | (1 << 30)),

        Keypad00 = (SDL2ScanCode.Keypad00 | (1 << 30)),
        Keypad000 = (SDL2ScanCode.Keypad000 | (1 << 30)),
        ThousandsSeparator = (SDL2ScanCode.ThousandsSeparator | (1 << 30)),
        DecimalSeparator = (SDL2ScanCode.DecimalSeparator | (1 << 30)),
        CurrencyUnit = (SDL2ScanCode.CurrencyUnit | (1 << 30)),
        CurrencySubUnit = (SDL2ScanCode.CurrencySubUnit | (1 << 30)),
        KeypadLeftParentes = (SDL2ScanCode.KeypadLeftParentes | (1 << 30)),
        KeypadRightParentes = (SDL2ScanCode.KeypadRightParentes | (1 << 30)),
        KeypadLeftBrace = (SDL2ScanCode.KeypadLeftBrace | (1 << 30)),
        KeypadRightBrace = (SDL2ScanCode.KeypadRightBrace | (1 << 30)),
        KeypadTab = (SDL2ScanCode.KeypadTab | (1 << 30)),
        KeypadBackspace = (SDL2ScanCode.KeypadBackspace | (1 << 30)),
        KeypadA = (SDL2ScanCode.KeypadA | (1 << 30)),
        KeypadB = (SDL2ScanCode.KeypadB | (1 << 30)),
        KeypadC = (SDL2ScanCode.KeypadC | (1 << 30)),
        KeypadD = (SDL2ScanCode.KeypadD | (1 << 30)),
        KeypadE = (SDL2ScanCode.KeypadE | (1 << 30)),
        KeypadF = (SDL2ScanCode.KeypadF | (1 << 30)),
        KeypadXor = (SDL2ScanCode.KeypadXor | (1 << 30)),
        KeypadPower = (SDL2ScanCode.KeypadPower | (1 << 30)),
        KeypadPercent = (SDL2ScanCode.KeypadPercent | (1 << 30)),
        KeypadLess = (SDL2ScanCode.KeypadLess | (1 << 30)),
        KeypadGreater = (SDL2ScanCode.KeypadGreater | (1 << 30)),
        KeypadAmpersand = (SDL2ScanCode.KeypadAmpersand | (1 << 30)),
        KeypadDoubleAmpersand = (SDL2ScanCode.KeypadDoubleAmpersand | (1 << 30)),
        KeypadVerticalBar = (SDL2ScanCode.KeypadVerticalBar | (1 << 30)),
        KeypadDoubleVerticalBar = (SDL2ScanCode.KeypadDoubleVerticalBar | (1 << 30)),
        KeypadColon = (SDL2ScanCode.KeypadColon | (1 << 30)),
        KeypadHash = (SDL2ScanCode.KeypadHash | (1 << 30)),
        KeypadSpace = (SDL2ScanCode.KeypadSpace | (1 << 30)),
        KeypadAt = (SDL2ScanCode.KeypadAt | (1 << 30)),
        KeypadExclamation = (SDL2ScanCode.KeypadExclamation | (1 << 30)),
        KeypadMemStore = (SDL2ScanCode.KeypadMemStore | (1 << 30)),
        KeypadMemRecall = (SDL2ScanCode.KeypadMemRecall | (1 << 30)),
        KeypadMemClear = (SDL2ScanCode.KeypadMemClear | (1 << 30)),
        KeypadMemAdd = (SDL2ScanCode.KeypadMemAdd | (1 << 30)),
        KeypadMemSubtract = (SDL2ScanCode.KeypadMemSubtract | (1 << 30)),
        KeypadMemMultiply = (SDL2ScanCode.KeypadMemMultiply | (1 << 30)),
        KeypadMemDivide = (SDL2ScanCode.KeypadMemDivide | (1 << 30)),
        KeypadPlusMinus = (SDL2ScanCode.KeypadPlusMinus | (1 << 30)),
        KeypadClear = (SDL2ScanCode.KeypadClear | (1 << 30)),
        KeypadClearEntry = (SDL2ScanCode.KeypadClearEntry | (1 << 30)),
        KeypadBinary = (SDL2ScanCode.KeypadBinary | (1 << 30)),
        KeypadOctal = (SDL2ScanCode.KeypadOctal | (1 << 30)),
        KeypadDecimal = (SDL2ScanCode.KeypadDecimal | (1 << 30)),
        KeypadHexadecimal = (SDL2ScanCode.KeypadHexadecimal | (1 << 30)),

        LeftControl = (SDL2ScanCode.LeftControl | (1 << 30)),
        LeftShift = (SDL2ScanCode.LeftShift | (1 << 30)),
        LeftAlt = (SDL2ScanCode.LeftAlt | (1 << 30)),
        LeftGui = (SDL2ScanCode.LeftGui | (1 << 30)),
        RightControl = (SDL2ScanCode.RightControl | (1 << 30)),
        RightShift = (SDL2ScanCode.RightShift | (1 << 30)),
        RightAlt = (SDL2ScanCode.RightAlt | (1 << 30)),
        RightGui = (SDL2ScanCode.RightGui | (1 << 30)),

        Mode = (SDL2ScanCode.Mode | (1 << 30)),

        AudioNext = (SDL2ScanCode.AudioNext | (1 << 30)),
        AudioPrevious = (SDL2ScanCode.AudioPrevious | (1 << 30)),
        AudioStop = (SDL2ScanCode.AudioStop | (1 << 30)),
        AudioPlay = (SDL2ScanCode.AudioPlay | (1 << 30)),
        AudioMute = (SDL2ScanCode.AudioMute | (1 << 30)),
        MediaSelect = (SDL2ScanCode.MediaSelect | (1 << 30)),
        WWW = (SDL2ScanCode.WWW | (1 << 30)),
        Mail = (SDL2ScanCode.Mail | (1 << 30)),
        Calculator = (SDL2ScanCode.Calculator | (1 << 30)),
        Computer = (SDL2ScanCode.Computer | (1 << 30)),
        AcSearch = (SDL2ScanCode.AcSearch | (1 << 30)),
        AcHome = (SDL2ScanCode.AcHome | (1 << 30)),
        AcBack = (SDL2ScanCode.AcBack | (1 << 30)),
        AcForward = (SDL2ScanCode.AcForward | (1 << 30)),
        AcStop = (SDL2ScanCode.AcStop | (1 << 30)),
        AcRefresh = (SDL2ScanCode.AcRefresh | (1 << 30)),
        AcBookmarks = (SDL2ScanCode.AcBookmarks | (1 << 30)),

        BrightnessDown = (SDL2ScanCode.BrightnessDown | (1 << 30)),
        BrightnessUp = (SDL2ScanCode.BrightnessUp | (1 << 30)),
        DisplaySwitch = (SDL2ScanCode.DisplaySwitch | (1 << 30)),
        KeypadDillumToggle = (SDL2ScanCode.KeypadDillumToggle | (1 << 30)),
        KeypadDillumDown = (SDL2ScanCode.KeypadDillumDown | (1 << 30)),
        KeypadDillumUp = (SDL2ScanCode.KeypadDillumUp | (1 << 30)),
        Eject = (SDL2ScanCode.Eject | (1 << 30)),
        Sleep = (SDL2ScanCode.Sleep | (1 << 30)),



    }
}
